version: '3.8'

# Find and replace "template-nodered-app" with your project name
name: template-nodered-app

services:
  node-red:
    container_name: template-nodered-app-nodered
    image: nodered/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
      - ./node-red/settings.js:/data/settings.js
    networks:
      - template-nodered-app-net
    environment:
      - TEST="Hello World"
    env_file:
      - path: dev.env
        required: true
  broker:
    container_name: template-nodered-app-broker
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
    networks:
      - template-nodered-app-net
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
      - ./broker/mosquitto-dev.conf:/mosquitto/config/mosquitto.conf

volumes:
  node-red-data:
    name: template-nodered-app-data

networks:
  template-nodered-app-net:
    name: template-nodered-app-net