version: '3.8'

# Find and replace "template-nodered-app" with your project name
name: template-nodered-app

services:
  node-red:
    container_name: template-nodered-app-nodered
    build: ./node-red
    ports:
      - "${NODE_RED_PORT:-1880}:1880"
    volumes:
      - node-red-data:/data
      - ./node-red/settings.js:/data/settings.js
    networks:
      - template-nodered-app-net
    env_file: "prod.env"

volumes:
  node-red-data:
    name: template-nodered-app-data

networks:
  template-nodered-app-net: