FROM nodered/node-red:latest

# Install pallette dependencies
RUN npm install @flowfuse/node-red-dashboard
RUN npm install node-red-contrib-mssql-plus
RUN npm install @nhimm/node-red-contrib-data-forge
RUN npm install node-red-contrib-filesystem